version: '2'

services:

  nginx:
    image: namelessmc/nginx:v2-pr9
    ports: ['80:80']
    volumes: ['./web:/data'] # same as php container
    # environment:
    #   PHP_FPM: php:9000
    depends_on: [php]
    restart: always

  php:
    image: namelessmc/php:v2-pr9
    volumes: ['./web:/data'] # same as web container
    restart: always

  db:
    image: mariadb
    volumes: ['./db:/var/lib/mysql']
    environment:
      MYSQL_ROOT_PASSWORD: nameless
      MYSQL_USER: nameless
      MYSQL_PASSWORD: nameless
      MYSQL_DATABASE: nameless
    restart: always
